# Generated by Django 3.2 on 2023-09-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followers_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
