# Generated by Django 3.2 on 2021-07-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_post_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(upload_to='posts/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(upload_to='posts/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(upload_to='posts/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(max_length=500),
        ),
    ]
