# Generated by Django 3.2 on 2021-08-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210731_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True, max_length=700)),
                ('image', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('image1', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('aboutus', models.TextField(blank=True, max_length=500)),
                ('aboutimage', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('project', models.TextField(blank=True, max_length=500)),
                ('projectimage', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('story', models.TextField(blank=True, max_length=1500)),
                ('storyimage', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('team', models.TextField(blank=True, max_length=1500)),
                ('teamimage', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
                ('whyus', models.TextField(blank=True, max_length=1500)),
                ('whyusimage', models.ImageField(blank=True, upload_to='aboutpage/%Y/%m/%d')),
            ],
        ),
    ]
