# Generated by Django 3.2 on 2021-09-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_post_image4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image4',
            field=models.ImageField(upload_to='posts/%Y/%m/%d'),
        ),
    ]
